"""Fast rHEALPix DGGS indexing powered by Rust.

Coordinates follow H3's Python convention: public functions accept and return
``(latitude, longitude)`` while the Rust core uses conventional GIS
``(longitude, latitude)`` ordering.
"""

from ._rhealpixdggs import (
    MAX_RESOLUTION,
    __version__,
    are_neighbor_cells,
    bbox_to_cells,
    cell_area,
    cell_contains,
    cell_covered_by,
    cell_covers,
    cell_crosses,
    cell_disjoint,
    cell_equals,
    cell_intersects,
    cell_overlaps,
    cell_touches,
    cell_within,
    cell_to_boundary,
    cell_to_boundary_densified,
    cells_to_boundaries,
    cell_to_centroid,
    cell_to_children,
    cell_to_latlng,
    cell_to_level_order_index,
    cell_to_neighbor,
    cell_to_neighbors,
    cell_to_parent,
    cell_to_post_order_index,
    cell_to_predecessor,
    cell_to_successor,
    compact_cells,
    get_base_cell_number,
    get_cell_region,
    get_cell_shape,
    get_resolution,
    grid_disk,
    grid_ring,
    int_to_str,
    is_valid_cell,
    latlng_to_cell,
    latlngs_to_cells,
    level_order_index_to_cell,
    line_to_cells,
    polygon_to_cells,
    post_order_index_to_cell,
    str_to_int,
    uncompact_cells,
)
from .compat import Cell, RHEALPixDGGS, WGS84_003
from . import geo, numpy

__all__ = [
    "MAX_RESOLUTION",
    "__version__",
    "Cell",
    "RHEALPixDGGS",
    "WGS84_003",
    "geo",
    "numpy",
    "are_neighbor_cells",
    "bbox_to_cells",
    "cell_area",
    "cell_contains",
    "cell_covered_by",
    "cell_covers",
    "cell_crosses",
    "cell_disjoint",
    "cell_equals",
    "cell_intersects",
    "cell_overlaps",
    "cell_touches",
    "cell_within",
    "cell_to_boundary",
    "cell_to_boundary_densified",
    "cells_to_boundaries",
    "cell_to_centroid",
    "cell_to_children",
    "cell_to_latlng",
    "cell_to_level_order_index",
    "cell_to_neighbor",
    "cell_to_neighbors",
    "cell_to_parent",
    "cell_to_post_order_index",
    "cell_to_predecessor",
    "cell_to_successor",
    "compact_cells",
    "get_base_cell_number",
    "get_cell_region",
    "get_cell_shape",
    "get_resolution",
    "grid_disk",
    "grid_ring",
    "int_to_str",
    "is_valid_cell",
    "latlng_to_cell",
    "latlngs_to_cells",
    "level_order_index_to_cell",
    "line_to_cells",
    "polygon_to_cells",
    "post_order_index_to_cell",
    "str_to_int",
    "uncompact_cells",
]
