from collections.abc import Sequence

MAX_RESOLUTION: int
__version__: str

def latlng_to_cell(latitude: float, longitude: float, resolution: int) -> str: ...
def latlngs_to_cells(
    coordinates: Sequence[tuple[float, float]], resolution: int
) -> list[str]: ...
def cell_to_latlng(cell: str) -> tuple[float, float]: ...
def cell_to_boundary(
    cell: str, trim_dart: bool = False
) -> list[tuple[float, float]]: ...
def get_cell_region(cell: str) -> str: ...
def get_cell_shape(cell: str) -> str: ...
def cell_to_neighbor(
    cell: str, direction: str, plane: bool = True
) -> str | None: ...
def cell_to_neighbors(cell: str, plane: bool = True) -> dict[str, str]: ...
def cell_to_parent(cell: str, resolution: int | None = None) -> str | None: ...
def cell_to_children(cell: str, resolution: int | None = None) -> list[str]: ...
def get_resolution(cell: str) -> int: ...
def get_base_cell_number(cell: str) -> int: ...
def is_valid_cell(cell: str) -> bool: ...
def str_to_int(cell: str) -> int: ...
def int_to_str(cell: int) -> str: ...
def cell_area(cell: str, unit: str = "m^2") -> float: ...
def compact_cells(cells: Sequence[str]) -> list[str]: ...
def uncompact_cells(cells: Sequence[str], resolution: int) -> list[str]: ...

def _cell_from_point(
    resolution: int,
    point: tuple[float, float],
    plane: bool = True,
    north_square: int = 0,
    south_square: int = 0,
) -> str | None: ...
def _cell_nucleus(
    cell: str,
    plane: bool = True,
    north_square: int = 0,
    south_square: int = 0,
) -> tuple[float, float]: ...
def _cell_vertices(
    cell: str,
    plane: bool = True,
    trim_dart: bool = False,
    north_square: int = 0,
    south_square: int = 0,
) -> list[tuple[float, float]]: ...
def _cell_neighbor(
    cell: str,
    direction: str,
    plane: bool = True,
    north_square: int = 0,
    south_square: int = 0,
) -> str | None: ...
def _cell_neighbors(
    cell: str,
    plane: bool = True,
    north_square: int = 0,
    south_square: int = 0,
) -> list[tuple[str, str]]: ...
def _cell_metric(
    resolution: int, metric: str, plane: bool = True
) -> float | None: ...
