from collections.abc import Sequence

MAX_RESOLUTION: int
__version__: str

def latlng_to_cell(latitude: float, longitude: float, resolution: int) -> str: ...
def latlngs_to_cells(
    coordinates: Sequence[tuple[float, float]], resolution: int
) -> list[str]: ...
def cell_to_latlng(cell: str) -> tuple[float, float]: ...
def cell_to_boundary(cell: str) -> list[tuple[float, float]]: ...
def cell_to_parent(cell: str, resolution: int | None = None) -> str | None: ...
def cell_to_children(cell: str, resolution: int | None = None) -> list[str]: ...
def get_resolution(cell: str) -> int: ...
def get_base_cell_number(cell: str) -> int: ...
def is_valid_cell(cell: str) -> bool: ...
def str_to_int(cell: str) -> int: ...
def int_to_str(cell: int) -> str: ...
def cell_area(cell: str, unit: str = "m^2") -> float: ...
def compact_cells(cells: Sequence[str]) -> list[str]: ...
def uncompact_cells(cells: Sequence[str], resolution: int) -> list[str]: ...

